// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbjhCCwakzWtuL3QH4epun4l4PxsSKgwk',
    appId: '1:799464802692:web:3b8507b24ffcf7e00db5d1',
    messagingSenderId: '799464802692',
    projectId: 'mental-wellness-app-f9de6',
    authDomain: 'mental-wellness-app-f9de6.firebaseapp.com',
    storageBucket: 'mental-wellness-app-f9de6.firebasestorage.app',
    measurementId: 'G-S262ZN8SYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4oCi06MjCHrm8nbIISWUKusaG-DCKMIw',
    appId: '1:799464802692:android:0e43637b936691e90db5d1',
    messagingSenderId: '799464802692',
    projectId: 'mental-wellness-app-f9de6',
    storageBucket: 'mental-wellness-app-f9de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDblgjbT6pMTGUHcwE3ucIEPxyg2kH7_Yc',
    appId: '1:799464802692:ios:877fb53fb46b60650db5d1',
    messagingSenderId: '799464802692',
    projectId: 'mental-wellness-app-f9de6',
    storageBucket: 'mental-wellness-app-f9de6.firebasestorage.app',
    iosBundleId: 'com.example.mentalWellnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDblgjbT6pMTGUHcwE3ucIEPxyg2kH7_Yc',
    appId: '1:799464802692:ios:877fb53fb46b60650db5d1',
    messagingSenderId: '799464802692',
    projectId: 'mental-wellness-app-f9de6',
    storageBucket: 'mental-wellness-app-f9de6.firebasestorage.app',
    iosBundleId: 'com.example.mentalWellnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbjhCCwakzWtuL3QH4epun4l4PxsSKgwk',
    appId: '1:799464802692:web:65f0bff4093119700db5d1',
    messagingSenderId: '799464802692',
    projectId: 'mental-wellness-app-f9de6',
    authDomain: 'mental-wellness-app-f9de6.firebaseapp.com',
    storageBucket: 'mental-wellness-app-f9de6.firebasestorage.app',
    measurementId: 'G-21Y8W2H5EL',
  );
}
